/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Chunk { }
export declare class Music { }
export declare class Mixer {
  constructor()
  loadWav(path: string): Chunk
  loadMusic(path: string): Music
  playChannel(chunk: Chunk, channel: number, loops: number): void
  playMusic(music: Music, loops: number): void
  haltChannel(channel: number): void
  haltMusic(): void
  volumeMusic(volume: number): number
  volumeChunk(channel: number, volume: number): number
}
